[package]
name = "ross-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ross-db = { path = "../ross-db" }
ross-derive = { path = "../ross-derive" }